### PR TITLE
Some Updates!

### PR DESCRIPTION
**Pull request by RoachxD**
I will make more Pull Requests tomorrow as I'm going to bed now..

### CODE REVIEW

**Comment by Balour** [comment]
Hey man, good job on the commits, I know I'm the most recent fork after detuks left, but there isn't even a thread for the scripts right now haha. Last I checked most were using packets and need major reworks. Havn'T had a chance to really look at them yet...

**Comment by RoachxD** [comment]
Yes, I know what you are talking about..
But, we can continue them, and by that I mean to.. well Fix them and Re-release them crediting Detuks for his awesome work.

Making a new thread for his Repo (Yours basically), with all the Scripts Linked after we Update them, and hopefully it will get pinned.

**Comment by Balour** [comment]
I know when he left there was great demand for HypaJungle, YasuoSharpV2 and RivenSharp

With the number of Riven scripts I'm guessing Hypajungle and YasuoSharpV2 are the 2 most important

**Comment by RoachxD** [comment]
True, could you give me your Skype ID or something?

**Comment by Balour** [comment]
rayfl0yd

**Pull request merged**
